FROM debian/base
LABEL maintainer="Quirin Pamp <pampq@cip.ifi.lmu.de>"

# install additional debian tools that are nice to have in interactive containers:
RUN apt-get -y install vim ranger less

CMD ["/bin/bash"]
